const data = {
  people: ['People', true],
  planets: ['Planets', true],
  films: ['Films', true],
  species: ['Species', true],
  vehicles: ['Vehicles', true],
  starships: ['Starships', true],
  home: ['Home', true],
  name: ['Name', true],
  height: ['Height', true],
  mass: ['Mass', true],
  hair_color: ['Hair Color', true],
  hair_colors: ['Hair Colors', true],
  skin_color: ['Skin Color', true],
  skin_colors: ['Skin Colors', true],
  eye_color: ['Eye Color', true],
  eye_colors: ['Eye Colors', true],
  birth_year: ['Birth Year', true],
  gender: ['Gender', true],
  homeworld: ['Home-World', true],
  classification: ['Classification', true],
  designation: ['Designation', true],
  average_height: ['Average Height', true],
  average_lifespan: ['Average Lifespan', true],
  language: ['Language', true],
  model: ['Model', true],
  manufacturer: ['Manufacturer', true],
  cost_in_credits: ['Cost in Credits', true],
  length: ['Length', true],
  max_atmosphering_speed: ['Max Atmospheric Speed', true],
  crew: ['Crew', true],
  passengers: ['Passengers', true],
  cargo_capacity: ['Cargo Capacity', true],
  consumables: ['Consumables', true],
  vehicle_class: ['Vehicle Class', true],
  hyperdrive_rating: ['Hyperdrive Rating', true],
  MGLT: ['MGLT', false],
  starship_class: ['Starship Class', true],
  pilots: ['Pilots', true],
  rotation_period: ['Rotation Period', true],
  orbital_period: ['Orbital Period', true],
  diameter: ['Diameter', true],
  climate: ['Climate', true],
  gravity: ['Gravity', true],
  terrain: ['Terrain', true],
  surface_water: ['Surface Water', true],
  population: ['Population', true],
  residents: ['Residents', true],
  black: ['Black', true],
  light: ['Light', true],
  brown: ['Brown', true],
  male: ['Male', true],
  female: ['Female', true],
  unknown: ['Unknown', true],
  fair: ['Fair', true],
  blue: ['Blue', true],
  blond: ['Blond', true],
  gold: ['Gold', true],
  yellow: ['Yellow', true],
  red: ['Red', true],
  white: ['White', true],
  none: ['None', true],
  grey: ['Grey', true],
  'blue-gray': ['Blue-Gray', true],
  auburn: ['Auburn', true],
  green: ['Green', true],
  orange: ['Orange', true],
  'green-tan': ['Green-Tan', true],
  hermaphrodite: ['Hermaphrodite', true],
  hazel: ['Hazel', true],
  pale: ['Pale', true],
  metal: ['Metal', true],
  dark: ['Dark', true],
  'brown mottle': ['Brown Mottle', true],
  'mottled green': ['Mottled Green', true],
  pink: ['Pink', true],
  tan: ['Tan', true],
  blonde: ['Blonde', true],
  silver: ['Silver', true],
  mammal: ['Mammal', true],
  sentient: ['Sentient', true],
  caucasian: ['Caucasian', true],
  asian: ['Asian', true],
  hispanic: ['Hispanic', true],
  amber: ['Amber', true],
  artificial: ['Artificial', true],
  indefinite: ['Indefinite', true],
  gray: ['Gray', true],
  golden: ['Golden', true],
  reptilian: ['Reptilian', true],
  gastropod: ['Gastropod', true],
  reptile: ['Reptile', true],
  amphibian: ['Amphibian', true],
  magenta: ['Magenta', true],
  purple: ['Purple', true],
  mammals: ['Mammals', true],
  vulpterish: ['Vulpterish', true],
  'pale pink': ['Pale Pink', true],
  indigo: ['Indigo', true],
  peach: ['Peach', true],
  insectoid: ['Insectoid', true],
  besalisk: ['Besalisk', true],
  wheeled: ['Wheeled', true],
  repulsorcraft: ['Repulsorcraft', true],
  starfighter: ['Starfighter', true],
  't-47 airspeeder': ['T-47 Airspeeder', true],
  airspeeder: ['Airspeeder', true],
  'space/planetary bomber': ['Space/Planetary Bomber', true],
  'assault walker': ['Assault Walker', true],
  walker: ['Walker', true],
  'sail barge': ['Sail Barge', true],
  'repulsorcraft cargo skiff': ['Repulsorcraft Cargo Skiff', true],
  speeder: ['Speeder', true],
  'landing craft': ['Landing Craft', true],
  submarine: ['Submarine', true],
  gunship: ['Gunship', true],
  transport: ['Transport', true],
  'wheeled walker': ['Wheeled Walker', true],
  'fire suppression ship': ['Fire Suppression Ship', true],
  'tri-fighter': ['Tri-Fighter', true],
  'droid starfighter': ['Droid Starfighter', true],
  'air speeder': ['Air Speeder', true],
  'droid tank': ['Droid Tank', true],
  corvette: ['Corvette', true],
  'assault starfighter': ['Assault Starfighter', true],
  yacht: ['Yacht', true],
  freighter: ['Freighter', true],
  'assault ship': ['Assault Ship', true],
  'capital ship': ['Capital Ship', true],
  'star destroyer': ['Star Destroyer', true],
  'arc-170': ['Arc-170', true],
  cruiser: ['Cruiser', true],
  arid: ['Arid', true],
  desert: ['Desert', true],
  temperate: ['Temperate', true],
  grasslands: ['Grasslands', true],
  mountains: ['Mountains', true],
  tropical: ['Tropical', true],
  jungle: ['Jungle', true],
  rainforests: ['Rainforests', true],
  frozen: ['Frozen', true],
  tundra: ['Tundra', true],
  'ice caves': ['Ice Caves', true],
  'mountain ranges': ['Mountain Ranges', true],
  murky: ['Murky', true],
  swamp: ['Swamp', true],
  jungles: ['Jungles', true],
  'gas giant': ['Gas Giant', true],
  forests: ['Forests', true],
  lakes: ['Lakes', true],
  'grassy hills': ['Grassy Hills', true],
  swamps: ['Swamps', true],
  cityscape: ['Cityscape', true],
  ocean: ['Ocean', true],
  rock: ['Rock', true],
  mountain: ['Mountain', true],
  barren: ['Barren', true],
  windy: ['Windy', true],
  scrublands: ['Scrublands', true],
  savanna: ['Savanna', true],
  canyons: ['Canyons', true],
  sinkholes: ['Sinkholes', true],
  hot: ['Hot', true],
  volcanoes: ['Volcanoes', true],
  'lava rivers': ['Lava Rivers', true],
  caves: ['Caves', true],
  rivers: ['Rivers', true],
  'artificial temperate': ['Artificial Temperate', true],
  'airless asteroid': ['Airless Asteroid', true],
  frigid: ['Frigid', true],
  glaciers: ['Glaciers', true],
  'ice canyons': ['Ice Canyons', true],
  humid: ['Humid', true],
  'fungus forests': ['Fungus Forests', true],
  moist: ['Moist', true],
  fields: ['Fields', true],
  'rock arches': ['Rock Arches', true],
  grass: ['Grass', true],
  polluted: ['Polluted', true],
  plains: ['Plains', true],
  urban: ['Urban', true],
  hills: ['Hills', true],
  oceans: ['Oceans', true],
  bogs: ['Bogs', true],
  savannas: ['Savannas', true],
  'rocky islands': ['Rocky Islands', true],
  seas: ['Seas', true],
  mesas: ['Mesas', true],
  deserts: ['Deserts', true],
  reefs: ['Reefs', true],
  islands: ['Islands', true],
  superheated: ['Superheated', true],
  'rocky deserts': ['Rocky Deserts', true],
  subartic: ['Subartic', true],
  valleys: ['Valleys', true],
  artic: ['Arctic', true],
  ash: ['Ash', true],
  'toxic cloudsea': ['Toxic Cloudsea', true],
  plateaus: ['Plateaus', true],
  verdant: ['Verdant', true],
  'rocky canyons': ['Rocky Canyons', true],
  'acid pools': ['Acid Pools', true],
  rocky: ['Rocky', true],
  vines: ['Vines', true],
  cities: ['Cities', true],
  savannahs: ['Savannahs', true],
  cliffs: ['Cliffs', true],
  title: ['Title', true],
  episode_id: ['Episode ID', true],
  opening_crawl: ['Opening Crawl', true],
  director: ['Director', true],
  producer: ['Producer', true],
  release_date: ['Release Date', true],
  characters: ['Characters', true]
}

export default data
